# Generated by Django 4.2.6 on 2024-01-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_expensecategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.TextField(default='bi bi-person-fill', max_length=20),
        ),
    ]
