# Generated by Django 4.2.6 on 2024-02-18 01:04

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_financialsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, validators=[myapp.models.validate_tag_name]),
        ),
    ]
